<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="9862" started-at="2017-12-30T19:19:18Z" finished-at="2017-12-30T19:19:28Z">
    <groups>
    </groups>
    <test name="ScreenShotTest" duration-ms="9861" started-at="2017-12-30T19:19:18Z" finished-at="2017-12-30T19:19:28Z">
      <class name="stepDefinition.FaceBook">
        <test-method status="FAIL" signature="FaceBook_Login()[pri:0, instance:stepDefinition.FaceBook@8bd1b6a]" name="FaceBook_Login" duration-ms="7445" started-at="2017-12-30T19:19:18Z" finished-at="2017-12-30T19:19:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<abc> but was:<Facebook - Log In or Sign Up>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<abc> but was:<Facebook - Log In or Sign Up>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at stepDefinition.FaceBook.FaceBook_Login(FaceBook.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$CountDownLatchedRunnable.run(ThreadUtil.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
    <test name="Test" duration-ms="5540" started-at="2017-12-30T19:19:18Z" finished-at="2017-12-30T19:19:24Z">
      <class name="stepDefinition.EA_StepDef">
        <test-method status="PASS" signature="EA_StepDef1()[pri:0, instance:stepDefinition.EA_StepDef@7dc7cbad]" name="EA_StepDef1" duration-ms="3236" started-at="2017-12-30T19:19:18Z" finished-at="2017-12-30T19:19:21Z">
        </test-method>
        <test-method status="PASS" signature="Login()[pri:1, instance:stepDefinition.EA_StepDef@7dc7cbad]" name="Login" duration-ms="1605" started-at="2017-12-30T19:19:21Z" finished-at="2017-12-30T19:19:23Z">
        </test-method>
        <test-method status="PASS" signature="perform()[pri:2, instance:stepDefinition.EA_StepDef@7dc7cbad]" name="perform" duration-ms="679" started-at="2017-12-30T19:19:23Z" finished-at="2017-12-30T19:19:24Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
